# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 16:33
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_experience_hobbies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=140)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
