# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_education'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hobbies',
            new_name='Hobby',
        ),
    ]
