# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20160715_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='dates',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
