# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 17:35
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_experience_precedence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
