# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20160715_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
