# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20160715_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='mcz_image',
            field=models.ImageField(blank=True, null=True, upload_to=b'headshot'),
        ),
    ]
