# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 17:00
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_info_mcz_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='main_title',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='sub_title',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
