# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20160805_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='resumes',
            field=models.FilePathField(blank=True, null=True, path=b'/Users/mzakany/Desktop/resume-django1/static/media/resumes'),
        ),
    ]
