# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_auto_20160806_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumefile',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
