# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20160805_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='precidence',
            field=models.IntegerField(default=0),
        ),
    ]
