# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20160805_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='precidence',
            new_name='precedence',
        ),
    ]
