# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20160805_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='href',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
