# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='precedence',
            field=models.IntegerField(default=0),
        ),
    ]
