# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_section_precedence'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
